name: Op

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # This runs the workflow every 6 hours

env:
  # Change these values if you have forked it for your own works
  GitHubMail: "chantalben293@hotmail.com"
  GitHubName: "Sonuown7"

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Git Configs & Install Dependencies
        run: |
          git config --global user.email "${{ env.GitHubMail }}"
          git config --global user.name "${{ env.GitHubName }}"
          
          chmod +x *
          pip install pyTelegramBotAPI requests
          chmod +x bgmi
          python3 m.py
